export enum SCREENS {
  AUTH_LOGIN = 'AUTH_LOGIN',
  TAB_ADDTASK = 'TAB_ADDTASK',
  TAB_CALENDAR = 'TAB_CALENDAR',
  TAB_CATEGORY = 'TAB_CATEGORY',
  TAB_MYDAY = 'TAB_MYDAY',
  TAB_PROFILE = 'TAB_PROFILE',
  TAB_SCREEN_STACK = 'TAB_SCREEN_STACK',
  DRAWER_SCREEN_STACK = 'DRAWER_SCREEN_STACK',
  AUTH_SCREEN_STACK = 'AUTH_SCREEN_STACK',
}
